# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kB75pHLzFcqf3_0S4QQFDDZTy_YvK-Dq
"""

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("images1.jpg")
cv2_imshow(rasm1)

rasm2=cv2.imread("images2.jpg")
cv2_imshow(rasm2)

rasm3=cv2.imread("images3.jpg")
cv2_imshow(rasm3)

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

oqqora=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)